let open = document.getElementById('open-btn'),
	name = document.getElementsByClassName('name-value'),
	budget = document.getElementsByClassName('budget-value'),
	choosedGoods = document.getElementsByClassName('goods-value'),
	items = document.getElementsByClassName('items-value'),
	employers = document.getElementsByClassName('employers-value'),
	discount = document.getElementsByClassName('discount-value'),
	isopen = document.getElementsByClassName('isopen-value'),
	btn = document.getElementsByTagName('button'),
	goods = document.getElementsByClassName('choose-goods'),
	itemsInput = document.querySelector('.choose-item'),
	timeInput = document.querySelector('.time-value'),
	budgetInput = document.querySelector('.count-budget-value'),
	empoers = document.querySelectorAll('.hire-employers-item');
	console.log(btn)
